services:
  db:
    image: postgres:latest
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - academic_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=academic
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  academic_volume:
